#!/bin/sh

sudo apt-get -y update
sudo apt-get -y install nginx curl nodejs-legacy

echo "packer: nginx"
sudo mkdir -p /var/log/nginx
sudo chown $INSTANCE_USER /var/log/nginx
sudo chmod -R 755 /var/log/nginx

echo "packer: nginx as a service"
sudo update-rc.d nginx defaults

echo "packer: nodejs"

mkdir -p $HOME/app
cp -r /tmp/scripts $HOME/app/scripts
